version: "2.1"

services:
  cli:
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - THEME
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/drush:/etc/drush:ro
  # Fake email
  mail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mail
  # Storybook URL
  # Acts as a reverse proxy and just proxies requests from storybook.explo.docksal to cli:6006
  storybook:
    image: wodby/nginx
    depends_on:
      - cli
    environment:
      NGINX_BACKEND_HOST: cli
      # Port 6006 Used for storybook in CLI container.
      NGINX_BACKEND_PORT: 6006
      NGINX_VHOST_PRESET: http-proxy
    labels:
      - io.docksal.virtual-host=storybook.${VIRTUAL_HOST}
